/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    paths: {
        'Ext.ux.picker.DateTime': './ux/picker/DateTime.js',
        'Ext.ux.field.DateTimePicker': './ux/field/DateTimePicker.js',
        'ux.signaturefield': './ux/signaturefield.js'
    }
});

Ext.application({
    models: [
        'Settings',
        'Session',
        'Patient',
        'PatientMetadata',
        'Routesheet'
    ],
    stores: [
        'SettingStore',
        'SessionStore',
        'PatientStore',
        'PatientLStore',
        'PatientMetaStore',
        'RoutesheetLStore',
        'RoutesheetStore',
        'PatientLocalStore',
        'VisitTypeStore'
    ],
    views: [
        'TabPanel',
        'PatientInfo',
        'RoutesheetForm'
    ],
    controllers: [
        'MainController',
        'LoginController',
        'SettingsController',
        'PatientsController',
        'RoutesheetController',
        'SyncController'
    ],
    name: 'MyApp',

    launch: function() {
        Ext.require('Ext.ux.picker.DateTime');
        Ext.require('Ext.ux.field.DateTimePicker');
        Ext.require('ux.signaturefield');
        Ext.create('MyApp.view.TabPanel', {fullscreen: true});
    }

});
