/*
 * File: app/model/Routesheet.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Routesheet', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'visit_date'
            },
            {
                name: 'start_time'
            },
            {
                name: 'end_time'
            },
            {
                name: 'latitude'
            },
            {
                name: 'longitude'
            },
            {
                name: 'visit_type_id'
            },
            {
                name: 'episode_id'
            },
            {
                name: 'patient_signature'
            },
            {
                name: 'treatment_id'
            },
            {
                name: 'patient_id'
            },
            {
                name: 'remarks'
            },
            {
                name: 'patient_name'
            }
        ]
    }
});