/*
 * File: app/store/PatientStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.PatientStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Patient'
    ],

    config: {
        model: 'MyApp.model.Patient',
        storeId: 'PatientStore',
        proxy: {
            type: 'jsonp',
            service_url_path: '/mobile/patients',
            reader: {
                type: 'json',
                record: 'patient'
            }
        },
        listeners: [
            {
                fn: 'onPatientsLoad',
                event: 'load'
            }
        ]
    },

    onPatientsLoad: function(store, records, successful, operation, eOpts) {
        if (!successful)
        return;

        this.localStore = Ext.StoreManager.lookup("PatientLocalStore");

        this.localStore.removeAll();

        var me = this;
        Ext.each(records, function(record) {
            console.log(record);
            me.localStore.add(record.copy());
        });
        me.localStore.sync();




    }

});