/*
 * File: app/store/RoutesheetLStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.RoutesheetLStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Routesheet'
    ],

    config: {
        data: [
            [
                1,
                '3/21/2013',
                '4:30AM',
                '5:30AM',
                100,
                200,
                1,
                3,
                4,
                'a',
                3,
                1
            ],
            [
                1,
                '4/11/2013',
                '5:20PM',
                '6:45PM',
                300,
                400,
                1,
                3,
                4,
                'a',
                3,
                2
            ]
        ],
        model: 'MyApp.model.Routesheet',
        storeId: 'RoutesheetLStore',
        proxy: {
            type: 'memory',
            reader: {
                type: 'array'
            }
        }
    }
});