/*
 * File: app/store/RoutesheetStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.RoutesheetStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Routesheet'
    ],

    config: {
        autoLoad: true,
        model: 'MyApp.model.Routesheet',
        storeId: 'RoutesheetStore',
        proxy: {
            type: 'ajax',
            batchActions: false,
            api: {
                create: '/app/Routesheet/create',
                read: '/app/Routesheet',
                update: '/app/Routesheet/update',
                destroy: '/app/Routesheet/delete'
            },
            reader: {
                type: 'json',
                clientIdProperty: 'id',
                idProperty: 'id'
            }
        }
    }
});