/*
 * File: app/store/SettingStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.SettingStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Settings'
    ],

    config: {
        autoLoad: false,
        model: 'MyApp.model.Settings',
        storeId: 'SettingStore',
        proxy: {
            type: 'ajax',
            batchActions: false,
            api: {
                create: '/app/UserSetting/create',
                read: '/app/UserSetting',
                update: '/app/UserSetting/update',
                destroy: '/app/UserSetting/delete'
            },
            noCache: false,
            reader: {
                type: 'json',
                idProperty: 'source_id'
            }
        },
        listeners: [
            {
                fn: 'onSettingsLoaded',
                event: 'load'
            }
        ]
    },

    onSettingsLoaded: function(store, records, successful, operation, eOpts) {
        onNetworkCheck(refreshDataIfRequired);
    }

});