/*
 * File: app/view/MyContainer1.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyContainer1', {
    extend: 'Ext.container.Container',

    height: 768,
    style: 'color:green;',
    width: 1024,
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    style: 'color:green;',
                    layout: {
                        type: 'border'
                    },
                    bodyPadding: 10,
                    manageHeight: false,
                    title: '',
                    items: [
                        {
                            xtype: 'tabpanel',
                            region: 'center',
                            margin: '5px',
                            activeTab: 0,
                            plain: true,
                            items: [
                                {
                                    xtype: 'panel',
                                    autoScroll: true,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    title: 'Living Situation/Psychosocial Assessment',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            border: 0,
                                            padding: '3px',
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    itemId: 'living_situation',
                                                    margin: '',
                                                    layout: {
                                                        type: 'anchor'
                                                    },
                                                    title: 'Living Situation',
                                                    items: [
                                                        {
                                                            xtype: 'checkboxgroup',
                                                            layout: {
                                                                align: 'stretch',
                                                                type: 'vbox'
                                                            },
                                                            fieldLabel: '',
                                                            items: [
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'living_situation_follow_up',
                                                                    boxLabel: 'Unchanged from Last Visit',
                                                                    inputValue: 'Unchanged from Last Visit'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'living_situation_follow_up',
                                                                    boxLabel: 'Update to Primary Caregiver',
                                                                    inputValue: 'Update to Primary Caregiver'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'living_situation_follow_up',
                                                                    boxLabel: 'Changes to Environmental Conditions',
                                                                    inputValue: 'Changes to Environmental Conditions'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            margin: ' 0 3px 3px 3px',
                                                            name: 'changed_living_situations',
                                                            fieldLabel: 'Changed'
                                                        }
                                                    ],
                                                    tools: [
                                                        {
                                                            xtype: 'tool',
                                                            type: 'pin'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    itemId: 'follow_up_plan',
                                                    margin: '3px',
                                                    layout: {
                                                        type: 'vbox'
                                                    },
                                                    title: 'Follow Up Plan',
                                                    items: [
                                                        {
                                                            xtype: 'checkboxgroup',
                                                            layout: {
                                                                align: 'stretch',
                                                                type: 'vbox'
                                                            },
                                                            fieldLabel: '',
                                                            items: [
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'follow_up_plan',
                                                                    boxLabel: 'Follow-up Visit',
                                                                    inputValue: 'Follow-up Visit'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'follow_up_plan',
                                                                    boxLabel: 'Confer with Team',
                                                                    inputValue: 'Confer with Team'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'follow_up_plan',
                                                                    boxLabel: 'Provide External Referral',
                                                                    inputValue: 'Provide External Referral'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'follow_up_plan',
                                                                    boxLabel: 'Discharge SW Services',
                                                                    inputValue: 'Discharge SW Services'
                                                                }
                                                            ]
                                                        }
                                                    ],
                                                    tools: [
                                                        {
                                                            xtype: 'tool',
                                                            type: 'pin'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            border: 0,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    itemId: 'emotional_status',
                                                    margin: '3px',
                                                    layout: {
                                                        type: 'anchor'
                                                    },
                                                    title: 'Emotional Status ',
                                                    items: [
                                                        {
                                                            xtype: 'checkboxgroup',
                                                            layout: {
                                                                align: 'stretch',
                                                                type: 'vbox'
                                                            },
                                                            fieldLabel: '',
                                                            items: [
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'emotional_status',
                                                                    boxLabel: 'Stable',
                                                                    inputValue: 'Stable'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'emotional_status',
                                                                    boxLabel: 'Tearful',
                                                                    inputValue: 'Tearful'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'emotional_status',
                                                                    boxLabel: 'Stressed',
                                                                    inputValue: 'Stressed'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'emotional_status',
                                                                    boxLabel: 'Angry',
                                                                    inputValue: 'Angry'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'emotional_status',
                                                                    boxLabel: 'Sad',
                                                                    inputValue: 'Sad'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'emotional_status',
                                                                    boxLabel: 'Withdrawn',
                                                                    inputValue: 'Withdrawn'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'emotional_status',
                                                                    boxLabel: 'Fearful',
                                                                    inputValue: 'Fearful'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'emotional_status',
                                                                    boxLabel: 'Anxious',
                                                                    inputValue: 'Anxious'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'emotional_status',
                                                                    boxLabel: 'Flat Affect',
                                                                    inputValue: 'Flat Affect'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            margin: '0 3px 5px 3px',
                                                            name: 'other_emotional_status',
                                                            fieldLabel: 'Other',
                                                            labelWidth: 40
                                                        }
                                                    ],
                                                    tools: [
                                                        {
                                                            xtype: 'tool',
                                                            type: 'pin'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    itemId: 'mental_status',
                                                    margin: '3px',
                                                    layout: {
                                                        type: 'anchor'
                                                    },
                                                    title: 'Mental Status',
                                                    items: [
                                                        {
                                                            xtype: 'checkboxgroup',
                                                            layout: {
                                                                align: 'stretch',
                                                                type: 'vbox'
                                                            },
                                                            fieldLabel: '',
                                                            items: [
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'mental_status',
                                                                    boxLabel: 'Oriented',
                                                                    inputValue: 'Oriented'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'mental_status',
                                                                    boxLabel: 'Confused',
                                                                    inputValue: 'Comatose'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'mental_status',
                                                                    boxLabel: 'Forgetful',
                                                                    inputValue: 'Forgetful'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'mental_status',
                                                                    boxLabel: 'Depressed',
                                                                    inputValue: 'Depressed'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'mental_status',
                                                                    boxLabel: 'Disoriented',
                                                                    inputValue: 'Disoriented'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'mental_status',
                                                                    boxLabel: 'Lethargic',
                                                                    inputValue: 'Lethargic'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'mental_status',
                                                                    boxLabel: 'Agitated',
                                                                    inputValue: 'Agitated'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            margin: '3px',
                                                            name: 'other1_mental_status',
                                                            fieldLabel: 'Other'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            margin: '3px',
                                                            name: 'other2_mental_status',
                                                            fieldLabel: 'Other'
                                                        }
                                                    ],
                                                    tools: [
                                                        {
                                                            xtype: 'tool',
                                                            type: 'pin'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    margin: '7px',
                                    padding: '3px',
                                    autoScroll: true,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    title: 'Interventions/Goals',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            border: 0,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    itemId: 'interventions',
                                                    margin: '0 3px 0 0',
                                                    layout: {
                                                        type: 'anchor'
                                                    },
                                                    title: 'Interventions',
                                                    items: [
                                                        {
                                                            xtype: 'checkboxgroup',
                                                            layout: {
                                                                align: 'stretch',
                                                                type: 'vbox'
                                                            },
                                                            fieldLabel: '',
                                                            items: [
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'interventions',
                                                                    boxLabel: 'Psychosocial Assessment',
                                                                    inputValue: 'Psychosocial Assessment'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'interventions',
                                                                    boxLabel: 'Community Res. Planning/Outreach',
                                                                    inputValue: 'Community Res. Planning/Outreach'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'interventions',
                                                                    boxLabel: 'Counsel re Disease Management',
                                                                    inputValue: 'Counsel re Disease Management'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'interventions',
                                                                    boxLabel: 'Community Res. Planning/Outreach',
                                                                    inputValue: 'Community Res. Planning/Outreach'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'interventions',
                                                                    boxLabel: 'Counseling re Family Coping',
                                                                    inputValue: 'Counseling re Family Coping'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'interventions',
                                                                    boxLabel: 'Stabilize Current Placement',
                                                                    inputValue: 'Stabilize Current Placement'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'interventions',
                                                                    boxLabel: 'Crisis Intervention',
                                                                    inputValue: 'Crisis Intervention'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'interventions',
                                                                    boxLabel: 'Determine/Locate Alt Placement',
                                                                    inputValue: 'Determine/Locate Alt Placement'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'interventions',
                                                                    boxLabel: 'Long-range Planning/Decision Making',
                                                                    inputValue: 'Long-range Planning/Decision Making'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'interventions',
                                                                    boxLabel: 'Financial Counseling and/or Referrals',
                                                                    inputValue: 'Financial Counseling and/or Referrals'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            margin: '0 0 5px 3px',
                                                            padding: '',
                                                            name: 'other_interventions',
                                                            fieldLabel: 'Other'
                                                        }
                                                    ],
                                                    tools: [
                                                        {
                                                            xtype: 'tool',
                                                            type: 'pin'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    itemId: 'goals',
                                                    margin: '0 0 0 3px',
                                                    layout: {
                                                        type: 'vbox'
                                                    },
                                                    title: 'Goals',
                                                    items: [
                                                        {
                                                            xtype: 'checkboxgroup',
                                                            layout: {
                                                                align: 'stretch',
                                                                type: 'vbox'
                                                            },
                                                            fieldLabel: '',
                                                            items: [
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'goals',
                                                                    boxLabel: 'Adequate Support System',
                                                                    inputValue: 'Adequate Support System'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'goals',
                                                                    boxLabel: 'Improved Client/Family Coping',
                                                                    inputValue: 'Improved Client/Family Coping'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'goals',
                                                                    boxLabel: 'Normal Grieving Process',
                                                                    inputValue: 'Normal Grieving Process'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'goals',
                                                                    boxLabel: 'Appropriate Goals set by Client/Family',
                                                                    inputValue: 'Appropriate Goals set by Client/Family'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'goals',
                                                                    boxLabel: 'Appropriate Community Res. Referrals',
                                                                    inputValue: 'Appropriate Community Res. Referrals'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'goals',
                                                                    boxLabel: 'Stable Placement Setting',
                                                                    inputValue: 'Stable Placement Setting'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    name: 'goals',
                                                                    boxLabel: 'Mobilization of Financial Resources',
                                                                    inputValue: 'Mobilization of Financial Resources'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            margin: '0 0 0 3px',
                                                            name: 'other_goals',
                                                            fieldLabel: 'Other'
                                                        }
                                                    ],
                                                    tools: [
                                                        {
                                                            xtype: 'tool',
                                                            type: 'pin'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'form',
                                    layout: {
                                        type: 'fit'
                                    },
                                    title: 'Strengths/Intevention Details/Plan Of Care',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            itemId: 'strength_intervention_details',
                                            margin: '7px',
                                            layout: {
                                                type: 'vbox'
                                            },
                                            title: 'intervention Details/Visit Goal Details /progress Towards Goals',
                                            items: [
                                                {
                                                    xtype: 'textareafield',
                                                    margin: '0 0 0 5px',
                                                    name: 'intervention_details',
                                                    fieldLabel: 'Intervention Details',
                                                    labelAlign: 'top',
                                                    cols: 100
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    margin: '3px 0 0 5px',
                                                    name: 'visit_goal_details',
                                                    fieldLabel: 'Visit Goal Details',
                                                    labelAlign: 'top',
                                                    cols: 100
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    margin: '3px 0 5px 5px',
                                                    name: 'progress_towards_goals',
                                                    fieldLabel: 'Progress Towards Goals',
                                                    labelAlign: 'top',
                                                    cols: 100
                                                }
                                            ],
                                            tools: [
                                                {
                                                    xtype: 'tool',
                                                    type: 'pin'
                                                }
                                            ]
                                        }
                                    ],
                                    tools: [
                                        {
                                            xtype: 'tool',
                                            type: 'pin'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});