/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyContainer', {
    extend: 'Ext.container.Container',

    height: 786,
    width: 1024,
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: 0,
                    layout: {
                        type: 'border'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'panel',
                            region: 'north',
                            border: 0,
                            margin: '5px',
                            layout: {
                                align: 'middle',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: 'Title'
                                }
                            ]
                        },
                        {
                            xtype: 'htmleditor',
                            region: 'center',
                            margin: '5px',
                            style: 'background-color: white;',
                            enableFont: false,
                            name: 'description',
                            fieldLabel: 'Description'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});