/*
 * File: app/view/RoutesheetForm.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.RoutesheetForm', {
    extend: 'Ext.form.Panel',

    config: {
        itemId: 'routesheet_form',
        items: [
            {
                xtype: 'datepickerfield',
                label: 'Visit Date',
                labelAlign: 'top',
                name: 'visit_date',
                placeHolder: ''
            },
            {
                xtype: 'datetimepickerfield',
                dateTimeFormat: 'h:i:A',
                picker: {
                    yearFrom: 1980,
                    minuteInterval: 1,
                    ampm: true,
                    slotOrder: [
                        'hour',
                        'minute',
                        'ampm'
                    ]
                },
                label: 'Visit Start Time',
                labelAlign: 'top',
                name: 'start_time'
            },
            {
                xtype: 'datetimepickerfield',
                dateTimeFormat: 'h:i:A',
                picker: {
                    yearFrom: 1980,
                    minuteInterval: 1,
                    ampm: true,
                    slotOrder: [
                        'hour',
                        'minute',
                        'ampm'
                    ]
                },
                label: 'Visit End Time',
                labelAlign: 'top',
                name: 'end_time'
            },
            {
                xtype: 'selectfield',
                itemId: 'visit_type',
                label: 'Visit Type',
                labelAlign: 'top',
                name: 'visit_type_id',
                placeHolder: 'Select Visit Type',
                displayField: 'description',
                hiddenName: 'visit_type_id',
                store: 'VisitTypeStore',
                valueField: 'id'
            },
            {
                xtype: 'numberfield',
                label: 'Latitude',
                labelAlign: 'top',
                name: 'latitude',
                readOnly: true
            },
            {
                xtype: 'numberfield',
                disabled: false,
                label: 'Longitude',
                labelAlign: 'top',
                name: 'longitude',
                readOnly: true
            },
            {
                xtype: 'textareafield',
                label: 'Remarks',
                labelAlign: 'top',
                name: 'remarks',
                placeHolder: 'Enter additional comments here...'
            },
            {
                xtype: 'hiddenfield',
                name: 'patient_id'
            },
            {
                xtype: 'signaturefield',
                ui: 'confirm',
                text: 'Tap for Patient Signature'
            }
        ]
    }

});