/*
 * File: app/view/TabPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TabPanel', {
    extend: 'Ext.tab.Panel',

    config: {
        id: 'main_tab',
        items: [
            {
                xtype: 'container',
                title: 'Home',
                iconCls: 'home',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'panel',
                        style: 'background-color:white',
                        ui: '',
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'toolbar',
                                docked: 'top',
                                ui: 'light',
                                title: 'FasterNotes'
                            },
                            {
                                xtype: 'image',
                                centered: true,
                                height: 250,
                                id: 'img',
                                ui: '',
                                width: 250,
                                src: './images/icon250.png'
                            },
                            {
                                xtype: 'label',
                                docked: 'bottom',
                                html: 'Copyright © 2013 FasterNotes',
                                itemId: 'version_info',
                                margin: '0 0 2 0',
                                style: 'color:grey;text-align:center;font-size:0.6em'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Patients',
                iconCls: 'team',
                itemId: 'patients',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'navigationview',
                        itemId: 'nav_view',
                        ui: '',
                        items: [
                            {
                                xtype: 'list',
                                title: 'Patients',
                                itemId: 'patients_list',
                                disableSelection: true,
                                itemTpl: [
                                    '<div>',
                                    '    <span class=\'list_first_line\'>{full_name}</span>',
                                    '    <span class=\'phone\'>({phone_number})</span>    ',
                                    '    <br/>',
                                    '    <span class=\'list_second_line\'>{location}</span>',
                                    '',
                                    '</div>'
                                ],
                                store: 'PatientLocalStore',
                                onItemDisclosure: false
                            }
                        ],
                        navigationBar: {
                            ui: 'light',
                            items: [
                                {
                                    xtype: 'button',
                                    align: 'right',
                                    hidden: true,
                                    itemId: 'save_routesheet',
                                    ui: 'action',
                                    text: 'Save'
                                }
                            ]
                        }
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Routesheets',
                iconCls: 'compose',
                itemId: 'routesheets',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'list',
                        itemId: 'routesheets_list',
                        allowDeselect: true,
                        itemTpl: [
                            '<div>',
                            '    <span class=\'list_first_line\'>{patient_name}</span>',
                            '    <span class=\'phone\'>{visit_type_id}</span>',
                            '    <br/>',
                            '    <span class=\'list_second_line\'>{visit_date:date(\'m/d/Y\')}</span>    ',
                            '    <span class=\'list_second_line\'>{start_time:date(\'g:i A\')} to {end_time:date(\'g:i A\')}</span>',
                            '</div>'
                        ],
                        store: 'RoutesheetStore'
                    },
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        ui: 'light',
                        title: 'Routesheets',
                        items: [
                            {
                                xtype: 'button',
                                align: 'right',
                                itemId: 'cmdDelete',
                                ui: 'decline',
                                text: 'Delete'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Synchronize',
                iconCls: 'refresh',
                itemId: 'synchronize',
                style: 'text-align:center',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'spacer',
                        height: 100
                    },
                    {
                        xtype: 'label',
                        html: 'Last synchronized at 10:00 pm,<br/>on 23rd August 2013',
                        itemId: 'sync_label',
                        margin: 5,
                        style: 'color:grey;text-align:center;font-size:0.8em'
                    },
                    {
                        xtype: 'button',
                        itemId: 'sync',
                        margin: 20,
                        ui: 'confirm',
                        text: 'Sync now'
                    },
                    {
                        xtype: 'button',
                        itemId: 'sync1',
                        margin: 20,
                        ui: 'action',
                        text: 'View Log'
                    },
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        ui: 'light',
                        title: 'Synchronize'
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Settings',
                iconCls: 'settings',
                itemId: 'settings',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        id: 'settings_toolbar',
                        ui: 'light',
                        title: 'Settings',
                        layout: {
                            pack: 'end',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                id: 'sign_in',
                                ui: 'action',
                                text: 'Save'
                            }
                        ]
                    },
                    {
                        xtype: 'formpanel',
                        id: 'settings_form',
                        layout: {
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'fieldset',
                                margin: '-30 0 0 0 ',
                                title: 'User Information',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        name: 'username',
                                        required: true,
                                        placeHolder: 'User name'
                                    },
                                    {
                                        xtype: 'passwordfield',
                                        name: 'password',
                                        required: true,
                                        placeHolder: 'Password'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                margin: '0 0 0 0',
                                title: 'Server URL',
                                items: [
                                    {
                                        xtype: 'urlfield',
                                        name: 'server_url',
                                        required: true,
                                        value: 'http://localhost:8080',
                                        placeHolder: 'http://example.com'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Sign Out',
                iconCls: 'reply',
                hidden: true
            }
        ],
        tabBar: {
            docked: 'bottom',
            id: 'tab_bar'
        }
    }

});