/*
 * File: app/view/MyContainer1.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyContainer1', {
    extend: 'Ext.container.Container',

    height: 469,
    style: 'color:green;',
    width: 1024,
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    style: 'color:green;',
                    layout: {
                        type: 'border'
                    },
                    bodyPadding: 10,
                    manageHeight: false,
                    title: '',
                    items: [
                        {
                            xtype: 'tabpanel',
                            region: 'center',
                            margin: '5px',
                            activeTab: 0,
                            plain: true,
                            layout: {
                                deferredRender: false,
                                type: 'card'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 711,
                                    width: 990,
                                    autoScroll: true,
                                    layout: {
                                        type: 'fit'
                                    },
                                    title: 'PROBLEMS/CONDITION ON  ADMISSION ',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            border: 0,
                                            itemId: 'problem_accordions',
                                            autoScroll: true,
                                            layout: {
                                                fill: false,
                                                type: 'accordion'
                                            },
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    itemId: 'treat_voice_disorder',
                                                    margin: '3px',
                                                    width: 760,
                                                    layout: {
                                                        type: 'vbox'
                                                    },
                                                    collapseFirst: false,
                                                    collapsed: false,
                                                    title: 'Treat voice disorder',
                                                    items: [
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'treat_voice_interventions',
                                                            fieldLabel: 'Interventions',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        },
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'treat_voice_response',
                                                            fieldLabel: 'Patient\'s Response/Outcome',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    itemId: 'treat_speech_disorder',
                                                    margin: '3px',
                                                    layout: {
                                                        type: 'vbox'
                                                    },
                                                    collapsed: true,
                                                    title: 'Treat speech disorder ',
                                                    items: [
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'treat_speach_interventions',
                                                            fieldLabel: 'Interventions',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        },
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'treat_speach_response',
                                                            fieldLabel: 'Patient\'s Response/Outcome',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    itemId: 'treat_dysphagia',
                                                    margin: '3px',
                                                    layout: {
                                                        type: 'vbox'
                                                    },
                                                    collapseFirst: false,
                                                    collapsed: true,
                                                    title: 'Treat dysphagia',
                                                    items: [
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'treat_dysphagia_interventions',
                                                            fieldLabel: 'Interventions',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        },
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'treat_dysphagia_response',
                                                            fieldLabel: 'Patient\'s Response/Outcome',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    itemId: 'treat_language_disorder',
                                                    margin: '3px',
                                                    layout: {
                                                        type: 'vbox'
                                                    },
                                                    collapsed: true,
                                                    title: 'Treat language disorder',
                                                    items: [
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'treat_language_interventions',
                                                            fieldLabel: 'Interventions',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        },
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'treat_language_response',
                                                            fieldLabel: 'Patient\'s Response/Outcome',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    itemId: 'aural_rehabilitation_training',
                                                    margin: '3px',
                                                    layout: {
                                                        type: 'vbox'
                                                    },
                                                    collapsed: true,
                                                    title: 'Aural Rehabilitation Training',
                                                    items: [
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'aural_rehabilitation_interventions',
                                                            fieldLabel: 'Interventions',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        },
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'aural_rehabilitation_response',
                                                            fieldLabel: 'Patient\'s Response/Outcome',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    itemId: 'treat_visual_disorder',
                                                    margin: '3px',
                                                    layout: {
                                                        type: 'vbox'
                                                    },
                                                    collapsed: true,
                                                    collapsible: false,
                                                    title: 'Treat Visual Disorder',
                                                    items: [
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'treat_visual_interventions',
                                                            fieldLabel: 'Interventions',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        },
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'treat_visual_response',
                                                            fieldLabel: 'Patient\'s Response/Outcome',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    itemId: 'treat_cognitive_disorder',
                                                    margin: '3px',
                                                    layout: {
                                                        type: 'vbox'
                                                    },
                                                    collapsed: true,
                                                    title: 'Treat Cognitive Disorder',
                                                    items: [
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'treat_cognitive_interventions',
                                                            fieldLabel: 'Interventions',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        },
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'treat_cognitive_response',
                                                            fieldLabel: 'Patient\'s Response/Outcome',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    itemId: 'other_problems_panel',
                                                    margin: '3px',
                                                    layout: {
                                                        type: 'vbox'
                                                    },
                                                    collapsed: true,
                                                    title: 'Other',
                                                    items: [
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'other_interventions',
                                                            fieldLabel: 'Interventions',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        },
                                                        {
                                                            xtype: 'textareafield',
                                                            margin: '5px 0 0 3px',
                                                            name: 'other_response',
                                                            fieldLabel: 'Patient\'s Response/Outcome',
                                                            labelAlign: 'right',
                                                            labelWidth: 200,
                                                            cols: 100
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    height: 692,
                                    title: 'Pain',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            height: 223,
                                            itemId: 'pain_panel',
                                            margin: '7px',
                                            bodyPadding: 3,
                                            title: 'Pain',
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    border: false,
                                                    height: 199,
                                                    layout: {
                                                        columns: 5,
                                                        type: 'table'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            height: 15,
                                                            width: 91,
                                                            text: 'Pain Location'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            height: 15,
                                                            width: 91,
                                                            text: 'Intensity(0-10)'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            height: 15,
                                                            width: 91,
                                                            text: 'Frequency'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            height: 15,
                                                            width: 91,
                                                            text: 'Description'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            height: 15,
                                                            width: 91,
                                                            text: 'Aggravating factors'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'pain_location1',
                                                            fieldLabel: ''
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            name: 'intensity1',
                                                            fieldLabel: '',
                                                            editable: false,
                                                            store: [
                                                                0,
                                                                1,
                                                                2,
                                                                3,
                                                                4,
                                                                5,
                                                                6,
                                                                7,
                                                                8,
                                                                9,
                                                                10
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'frequency1',
                                                            fieldLabel: ''
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'description1',
                                                            fieldLabel: ''
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'aggravating_factors1',
                                                            fieldLabel: ''
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'pain_location2',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            name: 'intensity2',
                                                            fieldLabel: '',
                                                            editable: false,
                                                            store: [
                                                                0,
                                                                1,
                                                                2,
                                                                3,
                                                                4,
                                                                5,
                                                                6,
                                                                7,
                                                                8,
                                                                9,
                                                                10
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'frequency2',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'description2',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'aggravating_factors2',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'pain_location3',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            name: 'intensity3',
                                                            fieldLabel: '',
                                                            editable: false,
                                                            store: [
                                                                0,
                                                                1,
                                                                2,
                                                                3,
                                                                4,
                                                                5,
                                                                6,
                                                                7,
                                                                8,
                                                                9,
                                                                10
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'frequency3',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'description3',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'aggravating_factors3',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'pain_location4',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            name: 'intensity4',
                                                            fieldLabel: '',
                                                            editable: false,
                                                            store: [
                                                                0,
                                                                1,
                                                                2,
                                                                3,
                                                                4,
                                                                5,
                                                                6,
                                                                7,
                                                                8,
                                                                9,
                                                                10
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'frequency4',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'description4',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'aggravating_factors4',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'pain_location5',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            name: 'intensity5',
                                                            fieldLabel: '',
                                                            editable: false,
                                                            store: [
                                                                0,
                                                                1,
                                                                2,
                                                                3,
                                                                4,
                                                                5,
                                                                6,
                                                                7,
                                                                8,
                                                                9,
                                                                10
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'frequency5',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'description5',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            width: 149,
                                                            name: 'aggravating_factors5',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'pain_location6',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            name: 'intensity6',
                                                            fieldLabel: '',
                                                            editable: false,
                                                            store: [
                                                                0,
                                                                1,
                                                                2,
                                                                3,
                                                                4,
                                                                5,
                                                                6,
                                                                7,
                                                                8,
                                                                9,
                                                                10
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'frequency6',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: 'description6',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            rowspan: 0,
                                                            name: 'aggravating_factors6',
                                                            fieldLabel: '',
                                                            labelAlign: 'top'
                                                        }
                                                    ]
                                                }
                                            ],
                                            tools: [
                                                {
                                                    xtype: 'tool',
                                                    type: 'pin'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    autoScroll: true,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    title: 'Narrative Response',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            border: 0,
                                            itemId: 'narrative_response',
                                            layout: {
                                                align: 'stretch',
                                                type: 'vbox'
                                            },
                                            title: 'Narrative Response',
                                            items: [
                                                {
                                                    xtype: 'fieldset',
                                                    flex: 1,
                                                    margin: '7px',
                                                    layout: {
                                                        type: 'vbox'
                                                    },
                                                    title: 'Narrative/interventions with patient/PCG response',
                                                    items: [
                                                        {
                                                            xtype: 'textareafield',
                                                            name: 'narrative_response',
                                                            fieldLabel: '',
                                                            labelAlign: 'top',
                                                            cols: 100
                                                        }
                                                    ]
                                                }
                                            ],
                                            tools: [
                                                {
                                                    xtype: 'tool',
                                                    type: 'pin'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});